name: esewa_flutter_sdk
description: This is an official Flutter plugin from eSewa to easily integrate eSewa payment into you flutter applications.
version: 2.3.0+16
author: eSewa Development
homepage: https://esewa.com.np/#/home
documentation: https://developer.esewa.com.np/#/flutter

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.10.6'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.f1soft.esewa.esewa_flutter_sdk
        pluginClass: EsewaFlutterSdkPlugin
      ios:
        pluginClass: EsewaFlutterSdkPlugin
