// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeIYzIt1maCf0uz_yTNdBhjZhQYDVuN5w',
    appId: '1:171037068739:web:56b3580cdcffee21fe8176',
    messagingSenderId: '171037068739',
    projectId: 'chat-app-ef5e6',
    authDomain: 'chat-app-ef5e6.firebaseapp.com',
    storageBucket: 'chat-app-ef5e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwT-mTCJwYZRNImDVrfrdIt5ysrxMbRRc',
    appId: '1:171037068739:android:7f1cfae04f2d6bf5fe8176',
    messagingSenderId: '171037068739',
    projectId: 'chat-app-ef5e6',
    storageBucket: 'chat-app-ef5e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQMc2dVp9colEvZ9NzkKGfFWulqIcKYRM',
    appId: '1:171037068739:ios:a6b04c70ae7fdcebfe8176',
    messagingSenderId: '171037068739',
    projectId: 'chat-app-ef5e6',
    storageBucket: 'chat-app-ef5e6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQMc2dVp9colEvZ9NzkKGfFWulqIcKYRM',
    appId: '1:171037068739:ios:d43159df601a914afe8176',
    messagingSenderId: '171037068739',
    projectId: 'chat-app-ef5e6',
    storageBucket: 'chat-app-ef5e6.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
